---
- hosts: front

  gather_facts: False
  become: False

 
  tasks:
#  - name: create a complete empty file
#    command: /usr/bin/touch /test/test.conf
 
  - name: create a new file with lineinfile
    lineinfile: dest=/tmp/test.conf 
                regexp='^' 
                line=''
                state=present
                create=True
                 
  - name: add a string to the new file
    lineinfile: dest=/tmp/test.conf
                regexp='^'
                line='Hello, World!'
                state=present
 
  #- name: add a multiline string to the file and delete the string from before
  # Be aware, with the given regex the string will be added everytime the playbook runs 
  #  lineinfile: dest=/tmp/test.conf 
  #              regexp='^'
  #              line='#This is a comment\n#Another comment\n#Another comment, again\n#Again a comment\n#The last comment'
  #              state=present

  - name: add a single line, in this case the same as the comment but uncommented
    lineinfile: dest=/tmp/test.conf 
                regexp='^Another'
                insertafter='^#Another'
                line='Another comment, no longer a comment'
                state=present
                
